#priority 2

//Plates
recipes.removeByRecipeName("thaumcraft:brassplate");
recipes.removeByRecipeName("thaumcraft:voidplate");

#Supremium infusion crystal
recipes.remove(<matc:supremiumcrystal>);
mods.thaumcraft.Infusion.registerRecipe("supremiumCrystal", "", <matc:supremiumcrystal>, 25, [<aspect:victus>, <aspect:mortuus>, <aspect:instrumentum>], <matc:superiumcrystal>, [<mysticalagriculture:crafting:4>, <actuallyadditions:item_crystal_empowered>, <extraplanets:tier5_items:8>, <mysticalagriculture:crafting:37>, <botania:manaresource:5>, <mysticalagriculture:crafting:4>, <bloodmagic:activation_crystal>, <astralsorcery:itemshiftingstar>.withTag({astralsorcery: {starAttunement: "astralsorcery.constellation.discidia"}})]);

#Sacrificial Dagger
recipes.remove(<bloodmagic:sacrificial_dagger>);
recipes.addShaped(<bloodmagic:sacrificial_dagger>, [[null, null, <thaumcraft:ingot:2>],[<thaumcraft:ingot>, <thaumcraft:ingot:2>, null], [<botania:manaresource:13>, <thaumcraft:ingot>, null]]);

//Tier 5 mystical agriculture seeds
recipes.remove(<mysticalagriculture:diamond_seeds>);
mods.thaumcraft.Infusion.registerRecipe("diamond", "", <mysticalagriculture:diamond_seeds>, 10, [<aspect:metallum>, <aspect:desiderium>, <aspect:vitreus>], <mysticalagriculture:crafting:21>, [<minecraft:diamond_block>, <mysticalagriculture:crafting:4>, <minecraft:diamond_block>, <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "vitreus"}]}), <minecraft:diamond_block>, <mysticalagriculture:crafting:4>, <minecraft:diamond_block>, <agricraft:agri_seed>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "resource:diamahlia_plant", agri_growth: 10 as byte})]);
recipes.remove(<mysticalagriculture:emerald_seeds>);
mods.thaumcraft.Infusion.registerRecipe("emerald", "", <mysticalagriculture:emerald_seeds>, 10, [<aspect:vitreus>, <aspect:desiderium>, <aspect:terra>], <mysticalagriculture:crafting:21>, [<minecraft:emerald_block>, <mysticalagriculture:crafting:4>, <minecraft:emerald_block>, <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "terra"}]}), <minecraft:emerald_block>, <mysticalagriculture:crafting:4>, <minecraft:emerald_block>, <agricraft:agri_seed>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "resource:emeryllis_plant", agri_growth: 10 as byte})]);
recipes.remove(<mysticalagriculture:wither_skeleton_seeds>);
mods.thaumcraft.Infusion.registerRecipe("witherskeleton", "", <mysticalagriculture:wither_skeleton_seeds>, 10, [<aspect:mortuus>, <aspect:spiritus>, <aspect:tenebrae>], <mysticalagriculture:crafting:21>, [<minecraft:skull:1>, <mysticalagriculture:crafting:4>, <minecraft:skull:1>, <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "tenebrae"}]}), <minecraft:skull:1>, <mysticalagriculture:crafting:4>, <minecraft:skull:1>, <thaumcraft:nitor_black>]);
recipes.remove(<mysticalagriculture:titanium_seeds>);
mods.thaumcraft.Infusion.registerRecipe("titanium", "", <mysticalagriculture:titanium_seeds>, 10, [<aspect:terra>, <aspect:metallum>, <aspect:machina>], <mysticalagriculture:crafting:21>, [<galacticraftplanets:asteroids_block:7>, <mysticalagriculture:crafting:4>, <galacticraftplanets:asteroids_block:7>, <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "machina"}]}), <galacticraftplanets:asteroids_block:7>, <mysticalagriculture:crafting:4>, <galacticraftplanets:asteroids_block:7>, <thaumcraft:nitor_blue>]);
recipes.remove(<mysticalagriculture:uranium_seeds>);
mods.thaumcraft.Infusion.registerRecipe("uranium", "", <mysticalagriculture:uranium_seeds>, 10, [<aspect:metallum>, <aspect:potentia>, <aspect:permutatio>], <mysticalagriculture:crafting:21>, [<nuclearcraft:ingot_block:4>, <mysticalagriculture:crafting:4>, <nuclearcraft:ingot_block:4>, <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "permutatio"}]}), <nuclearcraft:ingot_block:4>, <mysticalagriculture:crafting:4>, <nuclearcraft:ingot_block:4>, <thaumcraft:nitor_green>]);
recipes.remove(<mysticalagriculture:platinum_seeds>);
mods.thaumcraft.Infusion.registerRecipe("platinum", "", <mysticalagriculture:platinum_seeds>, 10, [<aspect:ignis>, <aspect:metallum>, <aspect:potentia>], <mysticalagriculture:crafting:21>, [<thermalfoundation:storage:6>, <mysticalagriculture:crafting:4>, <thermalfoundation:storage:6>, <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "potentia"}]}), <thermalfoundation:storage:6>, <mysticalagriculture:crafting:4>, <thermalfoundation:storage:6>, <agricraft:agri_seed>.withTag({agri_analyzed: 1 as byte, agri_strength: 10 as byte, agri_gain: 10 as byte, agri_seed: "resource:platiolus_plant", agri_growth: 10 as byte})]);
recipes.remove(<mysticalagriculture:iridium_seeds>);
mods.thaumcraft.Infusion.registerRecipe("iridium", "", <mysticalagriculture:iridium_seeds>, 10, [<aspect:ignis>, <aspect:alkimia>, <aspect:potentia>], <mysticalagriculture:crafting:21>, [<thermalfoundation:storage:7>, <mysticalagriculture:crafting:4>, <thermalfoundation:storage:7>, <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "potentia"}]}), <thermalfoundation:storage:7>, <mysticalagriculture:crafting:4>, <thermalfoundation:storage:7>, <thaumcraft:nitor_white>]);
recipes.remove(<mysticalagriculture:enderium_seeds>);
mods.thaumcraft.Infusion.registerRecipe("enderium", "", <mysticalagriculture:enderium_seeds>, 10, [<aspect:perditio>, <aspect:metallum>, <aspect:alkimia>], <mysticalagriculture:crafting:21>, [<thermalfoundation:storage_alloy:7>, <mysticalagriculture:crafting:4>, <thermalfoundation:storage_alloy:7>, <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "alkimia"}]}), <thermalfoundation:storage_alloy:7>, <mysticalagriculture:crafting:4>, <thermalfoundation:storage_alloy:7>, <thaumcraft:nitor_cyan>]);
recipes.remove(<mysticalagriculture:manyullyn_seeds>);
mods.thaumcraft.Infusion.registerRecipe("manyullyn", "", <mysticalagriculture:manyullyn_seeds>, 10, [<aspect:ignis>, <aspect:potentia>, <aspect:vitium>], <mysticalagriculture:crafting:21>, [<tconstruct:metal:2>, <mysticalagriculture:crafting:4>, <tconstruct:metal:2>, <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "vitium"}]}), <tconstruct:metal:2>, <mysticalagriculture:crafting:4>, <tconstruct:metal:2>, <thaumcraft:nitor_purple>]);
recipes.remove(<mysticalagriculture:vibrant_alloy_seeds>);
mods.thaumcraft.Infusion.registerRecipe("vibrantalloy", "", <mysticalagriculture:vibrant_alloy_seeds>, 10, [<aspect:lux>, <aspect:motus>, <aspect:sensus>], <mysticalagriculture:crafting:21>, [<enderio:block_alloy:2>, <mysticalagriculture:crafting:4>, <enderio:block_alloy:2>, <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "sensus"}]}), <enderio:block_alloy:2>, <mysticalagriculture:crafting:4>, <enderio:block_alloy:2>, <thaumcraft:nitor_lime>]);
recipes.remove(<mysticalagriculture:end_steel_seeds>);
mods.thaumcraft.Infusion.registerRecipe("endsteel", "", <mysticalagriculture:end_steel_seeds>, 10, [<aspect:ignis>, <aspect:tenebrae>, <aspect:lux>], <mysticalagriculture:crafting:21>, [<enderio:block_alloy:8>, <mysticalagriculture:crafting:4>, <enderio:block_alloy:8>, <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "lux"}]}), <enderio:block_alloy:8>, <mysticalagriculture:crafting:4>, <enderio:block_alloy:8>, <thaumcraft:nitor_white>]);
recipes.remove(<mysticalagriculture:terrasteel_seeds>);
mods.thaumcraft.Infusion.registerRecipe("terrasteel", "", <mysticalagriculture:terrasteel_seeds>, 10, [<aspect:metallum>, <aspect:praecantatio>, <aspect:herba>], <mysticalagriculture:crafting:21>, [<botania:storage:1>, <mysticalagriculture:crafting:4>, <botania:storage:1>, <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "herba"}]}), <botania:storage:1>, <mysticalagriculture:crafting:4>, <botania:storage:1>, <thaumcraft:nitor_lime>]);
recipes.remove(<mysticalagriculture:refined_obsidian_seeds>);
mods.thaumcraft.Infusion.registerRecipe("refinedobsidian", "", <mysticalagriculture:refined_obsidian_seeds>, 10, [<aspect:ignis>, <aspect:tenebrae>, <aspect:alienis>], <mysticalagriculture:crafting:21>, [<mekanism:basicblock:2>, <mysticalagriculture:crafting:4>, <mekanism:basicblock:2>, <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "alienis"}]}), <mekanism:basicblock:2>, <mysticalagriculture:crafting:4>, <mekanism:basicblock:2>, <thaumcraft:nitor_purple>]);
recipes.remove(<mysticalagriculture:desh_seeds>);
mods.thaumcraft.Infusion.registerRecipe("desh", "", <mysticalagriculture:desh_seeds>, 10, [<aspect:potentia>, <aspect:ignis>, <aspect:perditio>], <mysticalagriculture:crafting:21>, [<galacticraftplanets:mars:8>, <mysticalagriculture:crafting:4>, <galacticraftplanets:mars:8>, <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "perditio"}]}), <galacticraftplanets:mars:8>, <mysticalagriculture:crafting:4>, <galacticraftplanets:mars:8>, <thaumcraft:nitor_gray>]);
recipes.remove(<mysticalagriculture:starmetal_seeds>);
mods.thaumcraft.Infusion.registerRecipe("starmetal", "", <mysticalagriculture:starmetal_seeds>, 10, [<aspect:metallum>, <aspect:praecantatio>, <aspect:instrumentum>], <mysticalagriculture:crafting:21>, [<jaopca:block_blockastralstarmetal>, <mysticalagriculture:crafting:4>, <jaopca:block_blockastralstarmetal>, <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "instrumentum"}]}), <jaopca:block_blockastralstarmetal>, <mysticalagriculture:crafting:4>, <jaopca:block_blockastralstarmetal>, <thaumcraft:nitor_blue>]);
recipes.remove(<mysticalagriculture:rock_crystal_seeds>);
mods.thaumcraft.Infusion.registerRecipe("rockcrystal", "", <mysticalagriculture:rock_crystal_seeds>, 10, [<aspect:terra>, <aspect:vitreus>, <aspect:ordo>], <mysticalagriculture:crafting:21>, [<astralsorcery:blockcustomore>, <mysticalagriculture:crafting:4>, <astralsorcery:blockcustomore>, <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "ordo"}]}), <astralsorcery:blockcustomore>, <mysticalagriculture:crafting:4>, <astralsorcery:blockcustomore>, <thaumcraft:nitor_white>]);
recipes.remove(<mysticalagriculture:ender_amethyst_seeds>);
mods.thaumcraft.Infusion.registerRecipe("enderamethyst", "", <mysticalagriculture:ender_amethyst_seeds>, 10, [<aspect:vitreus>, <aspect:desiderium>, <aspect:praecantatio>], <mysticalagriculture:crafting:21>, [<biomesoplenty:gem_ore>, <mysticalagriculture:crafting:4>, <biomesoplenty:gem_ore>, <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "praecantatio"}]}), <biomesoplenty:gem_ore>, <mysticalagriculture:crafting:4>, <biomesoplenty:gem_ore>, <thaumcraft:nitor_magenta>]);
recipes.remove(<mysticalagriculture:draconium_seeds>);
mods.thaumcraft.Infusion.registerRecipe("draconium", "", <mysticalagriculture:draconium_seeds>, 10, [<aspect:motus>, <aspect:bestia>, <aspect:alienis>], <mysticalagriculture:crafting:21>, [<draconicevolution:draconium_block>, <mysticalagriculture:crafting:4>, <draconicevolution:draconium_block>, <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "alienis"}]}), <draconicevolution:draconium_block>, <mysticalagriculture:crafting:4>, <draconicevolution:draconium_block>, <thaumcraft:nitor_purple>]);
recipes.remove(<mysticalagriculture:yellorium_seeds>);
mods.thaumcraft.Infusion.registerRecipe("yellorium", "", <mysticalagriculture:yellorium_seeds>, 10, [<aspect:ignis>, <aspect:fabrico>, <aspect:aer>], <mysticalagriculture:crafting:21>, [<bigreactors:blockyellorium>, <mysticalagriculture:crafting:4>, <bigreactors:blockyellorium>, <thaumcraft:crystal_essence>.withTag({Aspects: [{amount: 1, key: "aer"}]}), <bigreactors:blockyellorium>, <mysticalagriculture:crafting:4>, <bigreactors:blockyellorium>, <thaumcraft:nitor_yellow>]);

print("- Thaumcraft.zs initialized");